#!/usr/bin/expect -f

set timeout 30
set host "45.93.101.65"
set port "65002"
set user "u977979652"
set password "qD*mX8v2%]+|;91"

spawn ssh -p $port $user@$host
expect {
    "Are you sure you want to continue connecting" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}

expect "$ "
send "cat .profile\r"

expect "$ "
send "cat .bashrc\r"

expect "$ "
send "exit\r"

expect eof
