#!/usr/bin/expect -f

set timeout 60
set host "45.93.101.65"
set port "65002"
set user "u977979652"
set password {4@iVyH5R$XXiv@8}

spawn ssh -p $port $user@$host
expect {
    "Are you sure" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}

expect "$ "
send "cd domains/acelabtutors.co.uk/public_html\r"

expect "$ "
send "grep -r \"dcb33f1eaf4e6ec3\" . | head -n 5\r"

expect "$ "
send "grep -r \"f8954e87e33a6447\" . | head -n 5\r"

expect "$ "
send "exit\r"
expect eof
